### ISSUE TITLE
[feat] Get google login token

### ISSUE THREAD

**Issue by wnehdals** [BCSDLab/JJBAKSA-ANDROID#5]
## 기능 요약
 - 구글로그인 후 토큰 획득
## 고려 사항
 - firebase auth로 구글로그인 개발
 - firebase 프로젝트 추가

**Comment by Ki-won** [comment]
920일 기준 / SocialLogin페이지 삭제, LoginActivity로 병합되어있는 형태
 
firebaseLoginActivity를 새로 생성하여 SocalLoginActivirty에서 호출해야하는지
SocalLoginActivity에 로직을 둬야할지 확실하지 않음.

**Comment by Ki-won** [comment]
override fun onActivityResult를 이용하고자 했으나 인증 관련공식문서 두 건의  설명이 달라 다른 하나를 따름.
(https://developers.google.com/identity/one-tap/android/get-saved-credentials?authuser)
lazy 및 함수를 생성하여 값을 할당하는 방법 -> 람다로 전환하여 추가시도.  작동은 잘합니다..?

**Comment by wnehdals** [comment]
Complete
